### ISSUE TITLE
[Questions] About the project

### ISSUE THREAD

**Issue by GrayJack** [cryptomilk/kernel-sdfat#3]
As for desktop Linux kernel, can I use it using the exfat-utils patched to don't use fuse?
Does it conflict with other exfat kernel modules like exfat-nofuse?

**Comment by cryptomilk** [comment]
You you probably need to modify the exfat-utils and replace `mount -t exfat` with `mount -t sdfat`. Beside that it should work.

**Comment by cryptomilk** [comment]
I would prefer patches :-)

**Comment by javelinanddart** [comment]
@GrayJack There's now a config option to allow using -t exfat (CONFIG_SDFAT_USE_FOR_EXFAT), if you were curious. I dunno what compile errors you're hitting, it compiles fine on 3.4, 3.10, 3.18, and 4.4 for arm and arm64, at least.

**Comment by GrayJack** [comment]
Thanks, I will test it latter.
